#imagesPath=D:/HSSC_UPLOADED_FILES/ACVetty/
#imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/ACVetty/
#imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/ASISteno/
#imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/ASI/
imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/SI/
#imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/CT23/
#imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/HC/

