#imagesPath=D:/HSSC_UPLOADED_FILES/ACVetty/
#imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/ACVetty/
#imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/ASISteno/ 
#imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/CT23/
#imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/HC/
# imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/ASI/
# imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads/candidateImages/SI/
# imagesPath=/Tomcat 7.0/webapps/ssb_uploads/candidateImages/MEDICAL/
#  imagesPath=D:/Arun 2026/ssb/ssb_images/MEDICAL
imagesPath=/opt/apache-tomcat-7.0.42/webapps/ssb_uploads26/candidateImages/MEDICAL


